### ISSUE TITLE
Configurable Problem Info Blocks

### ISSUE THREAD

**Issue by The-Dankest** [makethecontestgreatagain/open-contest#1]
Original issue: https://github.com/bjucps/open-contest/issues/1

Add a Contest configuration option: "Show Problem Info Blocks" with two values: On and Off. When On, problem information blocks "Problem Statement," "Input Format," "Output Format," and "Constraints" appear. When Off, problem information blocks do not appear.

**Comment by zrev2220** [comment]
Completed in 016af5ab998a16da8a2afb72a43e9ba168ae60e5
