### ISSUE TITLE
Contestant Submission History Table

### ISSUE THREAD

**Issue by The-Dankest** [makethecontestgreatagain/open-contest#13]
Original issue: https://github.com/bjucps/open-contest/issues/13

In the contestant /submissions view, replace the current display with a table that contains the following columns:

- Problem Title
- Submission date/time
- Language
- Result

Sort the table by problem, then submission date/time (most recent on top).

Result should be the judging result, unless the submission status is "review," in which case it should be "Pending review".

When the user clicks on an entry in the table, display a popup that shows the source code. For inspiration on how to do this part, review the /judge view, which does something similar.

**Comment by zrev2220** [comment]
Done I think. Remember to uncomment https://github.com/makethecontestgreatagain/open-contest/blob/87c143daf8a9b3177df13e09f783a41c70a39c3c/src/main/generator/pages/submissions.py#L33

**Comment by zrev2220** [comment]
TODO: Forgot to sort by problem then by time. Need to figure that out.

**Comment by zrev2220** [comment]
Finished!
