### ISSUE TITLE
Configurable Sample Data Tie Breaker

### ISSUE THREAD

**Issue by The-Dankest** [makethecontestgreatagain/open-contest#2]
Original issue: https://github.com/bjucps/open-contest/issues/2

Add a Contest configuration option: "Sample Data Breaks Ties" with two values: On and Off.

- When On, the scoring system should use incorrect solutions that have correct output for sample data to break ties.
- When Off, incorrect solutions should not be used to break ties.

**Comment by andrew-avinante** [comment]
Done
