### ISSUE TITLE
Auto Rejudge

### ISSUE THREAD

**Issue by The-Dankest** [makethecontestgreatagain/open-contest#5]
Original issue: https://github.com/bjucps/open-contest/issues/5

Add a "Rejudge All" button to each problem listed in the /problems view of the Admin user. When clicked, the system should rejudge all submissions of that problem.

The rejudging process should work as follows:

```
let ctime = current time. 
for each contestant:
  for each of the contestant's submissions with timestamp < ctime:
    if the submission's result != "reject":
       rejudge the submission
```

**Comment by zrev2220** [comment]
Will need to merge with #6

**Comment by zrev2220** [comment]
Close to finished in https://github.com/makethecontestgreatagain/open-contest/commit/084e9990d674813b6d265a43f218da9d34a72fca
