### ISSUE TITLE
Improve Autojudge

### ISSUE THREAD

**Issue by The-Dankest** [makethecontestgreatagain/open-contest#7]
Original issue: https://github.com/bjucps/open-contest/issues/7

The current autojudge algorithm marks any deviation from the expected output (other than certain whitespace issues) as "Wrong answer." Improve the autojudge algorithm to identify "Extra output" and "Incomplete output" (issue #6) cases, as follows:

* If the actual output contains all of the lines of the expected output, in the correct order, but there are additional lines (either inserted in the middle, or at the end), mark the result "extra output."

* If the actual output contains one or more of the lines of the expected output in the correct order, but it is missing some of the lines (either in the middle, or at the end), and there are no additional lines, mark the result "incomplete output."

**Comment by zrev2220** [comment]
Done pending Dr. Schaub's ruling on whether additions to the last line of answers or truncations from the last line of output count as extra/incomplete or WA

**Comment by zrev2220** [comment]
Well, not done. Need to modify check to linear scan for missing/additional lines I guess. 😞

**Comment by zrev2220** [comment]
Complete

**Comment by zrev2220** [comment]
Reopen: Need to pull @lutyputy 's bugfix here https://github.com/makethecontestgreatagain/open-contest/blob/15af441a3ea8e9257aa2228f1e9eada7b4dd9531/src/main/serve/scripts/script.js#L175 when he's done that, then can close.
